exports.up = function(knex, Promise) {
    return knex.schema.createTable('vivazul_cso_root.cadastros', table => {
        table.engine('InnoDB')
        table.charset('utf8mb4')
        table.collate('utf8mb4_general_ci')
        table.increments('id').primary()
        table.integer('evento').notNull()
        table.string('created_at').notNull()
        table.string('updated_at')
        table.integer('status').defaultTo(0).notNull().comment('Status do registro (INATIVO:0; ATIVO:10; EXCLUÍDO:99)')
        table.integer('prospect',1).defaultTo(1).notNull().comment('Prospecto (Não: 0; Sim: 1)')
        table.integer('id_params_tipo').unsigned().notNull().comment('Tipo de cliente (Arquiteto, Cliente, Fornecedor)')
        table.integer('id_params_atuacao',10).unsigned().notNull().comment('Área de atuação (Chave estrangeira com a tabela CLI_DOM.local_params)')
        table.string('cpf_cnpj').unique().notNull().comment('CPF ou CNPJ')
        table.string('rg_ie').comment('RG(PF) ou Inscrição Estadual(PJ)')
        table.string('nome').notNull().comment('Nome ou razão social')
        table.integer('id_params_sexo').unsigned().comment('Sexo(apenas PF) (Masc: 0; Fem: 1; Outro: 2)')
        table.string('aniversario').comment('Nascimento(PF) | Fundação(PJ)')
        table.integer('id_params_p_nascto').unsigned().comment('Nacionalidade')
        table.string('cim').comment('CIM')
        table.string('doc_esp').comment('Doc. Especial')
        table.boolean('mala').comment('Aceita Mala')
        table.string('telefone').comment('Telefone')
        table.string('email').comment('E-mail')
        table.string('observacao',2500).comment('Observações do cliente')
        table.foreign('id_params_tipo').references('id').inTable('local_params').onUpdate('Cascade').onDelete('NO ACTION')
        table.foreign('id_params_atuacao').references('id').inTable('local_params').onUpdate('Cascade').onDelete('NO ACTION')
        table.foreign('id_params_sexo').references('id').inTable('vivazul_api.params').onUpdate('Cascade').onDelete('NO ACTION')
        table.foreign('id_params_p_nascto').references('id').inTable('vivazul_api.params').onUpdate('Cascade').onDelete('NO ACTION')
    })
};

exports.down = function(knex, Promise) {
    return knex.schema.dropTable('vivazul_cso_root.cadastros')
};