const { migrationClientSchema, db } = require('../.env')

exports.up = function (knex, Promise) {
    return knex.schema.createTable(migrationClientSchema + '.empresa', table => {
        table.engine('InnoDB')
        table.charset('utf8mb4')
        table.collate('utf8mb4_general_ci')
        table.increments('id').primary()
        table.integer('evento').notNull()
        table.string('created_at').notNull()
        table.string('updated_at')
        table.integer('status').defaultTo(0).notNull().comment('Status do registro (INATIVO:0; ATIVO:10; EXCLUÍDO:99)')
        table.string('razaosocial', 255).comment('Razão social do cadastro')
        table.string('fantasia', 255).comment('Nome fantasia da empresa')
        table.string('cpf_cnpj_empresa', 255).comment('CNPJ do cadastro')
        table.string('ie', 255).comment('Inscrição estadual')
        table.string('ie_st', 255).comment('Inscrição estadual do substituto tributário')
        table.string('im', 255).comment('nscrição municipal')
        table.string('cnae', 255).comment('CNAE')
        table.string('cep', 8).notNull().comment('Cep')
        table.string('logradouro', 255).notNull().comment('Logradouro')
        table.string('nr', 255).notNull().comment('Número')
        table.string('complnr', 255).comment('Complemento')
        table.string('bairro', 255).comment('Bairro')
        table.string('cidade', 255).notNull().comment('Cidade')
        table.string('uf', 2).notNull().comment('Estado')
        table.string('ibge', 8).comment('IBGE')
        table.string('geo_ltd', 255).comment('Geo. latd')
        table.string('geo_lng', 255).comment('Geo. lng')
        table.text('contato').comment('Contato da empresa')
        table.string('tel1', 255).comment('Telefone 1')
        table.string('tel2', 255).comment('Telefone 2')
        table.string('email', 255).comment('Email geral')
        table.string('email_at', 255).comment('Email da At')
        table.string('email_comercial', 255).comment('Email comercial')
        table.string('email_financeiro', 255).comment('Email do financeiro')
        table.string('email_rh', 255).comment('Email do RH')
        table.integer('id_cadas_resplegal', 10).unsigned().comment('Responsável legal perante a Receita Federal')
        table.integer('id_uploads_logo', 10).unsigned().comment('Logomarca da empresa')
        table.foreign('id_cadas_resplegal').references('id').inTable(migrationClientSchema + '.cadastros').onUpdate('Cascade').onDelete('NO ACTION')
        table.foreign('id_uploads_logo').references('id').inTable(db.database + '.uploads').onUpdate('Cascade').onDelete('Cascade')
    })
};

exports.down = function (knex, Promise) {
    return knex.schema.dropTable('vivazul_bceaa5.empresa')
};