exports.up = function(knex, Promise) {
    return knex.schema.createTable('vivazul_cso_root.fin_lancamentos', table => {
        table.engine('InnoDB')
        table.charset('utf8mb4')
        table.collate('utf8mb4_general_ci')
        table.increments('id').primary()
        table.integer('evento').notNull()
        table.string('created_at').notNull()
        table.string('updated_at')
        table.integer('status').default(0).notNull().comment('Status do registro (INATIVO:0; ATIVO:10; EXCLUÍDO:99)')
        table.specificType('tp_cta', 'char(1)').comment('+=Receber;-=Pagar')
        table.integer('id_empresa',10).unsigned().notNull().default(0).comment('Codigo relacional com a tabela sis_demp')
        table.integer('id_cadastros',10).unsigned().notNull().default(0).comment('Codigo relacional com a tabela de cadastros')
        table.integer('id_centro_custo',10).unsigned().notNull().default(0).comment('Codigo relacional com a tabela fin_centro_custo')
        table.string('tipoDocumento',255).comment('Documento gerado: CF, NF-e, NFS-e')
        table.string('doc_fiscal',255).default(0).comment('Nota fiscal do lancamento')
        table.specificType('data_lanc','char(10)').comment('Data do lancamento da conta no sistema')
        table.specificType('data_vencimento','char(10)').comment('Data de vencimento programado para a conta')
        table.specificType('data_pagto','char(10)').comment('Data real que aconteceu o pagamento')
        table.double('valor_bruto',11,2).default(0.00).comment('Valor bruto da conta')
        table.double('valor_bruto_nf',11,2).default(0.00).comment('Valor bruto da nota fiscal')
        table.double('valor_retencao',11,2).default(0.00).comment('Valor da retenção. Este campo será impresso na duplicata.')
        table.double('valor_liquido',11,2).default(0.00).comment('Valor liquido da conta')
        table.string('descricao_retencao',250).comment('Descrição abreviada do motivo da retencao. Este campo será impresso na duplicata.')
        table.double('valor_vencimentos',11,2).default(0.00).comment('Valor bruto da conta')
        table.double('valor_nota_fiscal',11,2).default(0.00).comment('Valor total da nota fiscal para impressão na duplicata')
        table.string('duplicata',255).comment('Duplicata da conta gerada no faturamento')
        table.integer('duplicata_impr',1).default(0).comment('Quantidade de vezes que a duplicata foi impresso')
        table.string('descricao_conta',100).comment('Descrição da conta')
        table.string('obs_da_conta',2500).comment('Observacao da conta')
        table.string('vencimento',3).comment('Parcela da conta. Ex.')
        table.string('forma_pagto',255).comment('Forma de pagamento utilizada')
        table.string('doc_pagto',255).comment('Documento que quitou o pagamento')
        table.specificType('situacao','char(1)').defaultTo("0").comment('Situacao:-1-Ainda não é considerado duplicata pois não foi impresso;0-Todos;1-Pendente;2-Cancelado;3-Quitado;4-Conciliado')
        table.string('motiv_cancel',255).comment('Caso situacao=2 descrever o motivo do cancelamento')
        table.foreign('id_cadastros').references('id').inTable('cadastros').onUpdate('Cascade').onDelete('NO ACTION')
        table.foreign('id_empresa').references('id').inTable('empresa').onUpdate('Cascade').onDelete('NO ACTION')
        table.foreign('id_centro_custo').references('id').inTable('fin_cc').onUpdate('Cascade').onDelete('NO ACTION')
    })
};

exports.down = function(knex, Promise) {
    return knex.schema.dropTable('vivazul_cso_root.fin_lancamentos')
};